### PR TITLE
Include it globally 

### PR DESCRIPTION
**Pull request by wijiler**
just so if people dont know how to include it globally they can

### CODE REVIEW

**Comment by rexim** [comment]
@wijiler but what if people don't know how to include files at all? Maybe we should document that too?

**Comment by wijiler** [comment]
@rexim ah sure I'll try and document how I interpret that

**Comment by wijiler** [comment]
k done!

**Comment by rexim** [comment]
But what if somebody does not know what sudo is? Should we document that too?

**Comment by wijiler** [comment]
> But what if somebody does not know what sudo is? Should we document that too?

I said what sudo does in it

**Comment by wijiler** [comment]
anyways include this if you want idrc

**Comment by wijiler** [comment]
a

**Pull request closed without merging**
